### ISSUE TITLE
如何开始游玩整合包？

### ISSUE THREAD

**Issue by DeathOctober** [canoeStudio/Farm-Story-Remastered#4]
首先，任务方面不知为何只有一个任务，而且我开了编辑模式也看不到其他隐藏式任务。然后就是生存工具的获取，我很迷茫（我选奖励箱开局给的镐子）挖一下石头就爆了，但我找不到任何其他工具的制作方式，我甚至连木板的合成都找不到，倒是有个合成，但他需要斧子，我又没有斧子我不知道该怎么进行下去，我尝试把目标放到燧石上面，但燧石合成并没有镐子等一类工具，我想不通

**Comment by Lonelyxiya** [comment]
你好，这个整合包暂时是半成品，后续会支持多任务或者多国语言支持 你可以先把木头放了在撸了。

**Comment by Lonelyxiya** [comment]
正式版恐怕明年出
